CREATE TABLE IF NOT EXISTS computers
(
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS versions
(
    id  INTEGER PRIMARY KEY AUTOINCREMENT,
    hex varchar(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS grids
(
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    width     INTEGER NOT NULL,
    height    INTEGER NOT NULL,
    agents    INTEGER NOT NULL,
    waypoints INTEGER NOT NULL,
    infill    INTEGER NOT NULL,
    data      TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS runs
(
    version_id  INTEGER  NOT NULL REFERENCES versions (id) ON DELETE SET NULL ON UPDATE CASCADE,
    grid_id     INTEGER  NOT NULL REFERENCES grids (id) ON DELETE CASCADE ON UPDATE CASCADE,
    computer_id INTEGER  NOT NULL REFERENCES computers (id) ON DELETE SET NULL ON UPDATE CASCADE,
    thread      INTEGER  NOT NULL,
    time_limit  DECIMAL  NOT NULL,
    runtime     DECIMAL,
    finished    INTEGER  NOT NULL DEFAULT 0,
    timestamp   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (version_id, grid_id, computer_id)
);